resources:
  repositories:
  - repository: Repo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: MyGitHubServiceConnection
    name: kalsor/nginx_test1

trigger:
- main

jobs:
  - job: job1
    steps:
    - script: "hostname"
      displayName: 'Run a one-line script'
    - script: "docker ps"
      displayName: "Run2"
