resources:
  repositories:
  - repository: Repo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: MyGitHubServiceConnection
    name: kalsor/nginx_test1
4trigger:
- main

stages: 
- stage: stage1
  jobs:
  - job: job1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: ""
      displayName: 'Run a one-line script'

- stage: stage2
  jobs:
  - job: importantjob
    pool:
      vmImage: 'windows-latest'
    steps:
      - pwsh: 'write-output "I do nothing"'